using Moodex.Models;
using Moodex.Models.Manifests;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using System.Text.Json;

namespace Moodex.Services
{
    public class AutoHotKeyScriptService : IAutoHotKeyScriptService
    {
        private readonly string _autoHotKeyExecutable;

        public AutoHotKeyScriptService()
        {
            _autoHotKeyExecutable = Path.Combine(AppContext.BaseDirectory, "External Tools", "AutoHotKey", "AutoHotkey64.exe");
        }

        public string CreateScript(GameInfo game)
        {
            // Determine game root folder
            var gameRoot = !string.IsNullOrEmpty(game.GameRootPath)
                ? game.GameRootPath
                : FindGameMainFolder(game.FileSystemPath, game.Name) ?? throw new InvalidOperationException($"Could not determine game root for: {game.FileSystemPath}");

            // Prompt for script name
            var inputFolder = Path.Combine(gameRoot, "input");
            Directory.CreateDirectory(inputFolder);

            var owner = System.Windows.Application.Current?.MainWindow;
            var dialog = new Moodex.Views.Utilities.InputOneFieldDialog("Add Script", "Enter a name for your script:", "My Script");
            dialog.Owner = owner;
            if (dialog.ShowDialog() != true || string.IsNullOrWhiteSpace(dialog.InputText))
                throw new OperationCanceledException("User cancelled script creation");

            var baseName = SanitizeFileName(dialog.InputText.Trim());
            var txtPath = Path.Combine(inputFolder, baseName + ".txt");
            var ahkPath = Path.Combine(inputFolder, baseName + ".ahk");

            // Create a basic template in TXT for editing
            var template = $@"; Input Script for {game.Name}
; Saved as .txt for editing. Moodex copies this into a .ahk at launch.
; Game Path: {game.FileSystemPath}

; Example mappings:
; F1::Send, {{Enter}}
; ^j::Send, My Text
";
            if (!File.Exists(txtPath)) File.WriteAllText(txtPath, template);
            if (!File.Exists(ahkPath)) File.WriteAllText(ahkPath, "; generated by Moodex\n");

            game.HasAutoHotKeyScript = true;

            // persist to manifest
            UpdateManifestScripts(game, man =>
            {
                man.InputScripts ??= new List<InputScriptEntry>();
                if (!man.InputScripts.Any(s => string.Equals(s.Name, baseName, StringComparison.OrdinalIgnoreCase)))
                {
                    man.InputScripts.Add(new InputScriptEntry { Name = baseName, Enabled = true });
                }
            });

            // reflect in runtime list
            if (!game.InputScripts.Any(s => s.Name.Equals(baseName, StringComparison.OrdinalIgnoreCase)))
                game.InputScripts.Add(new InputScriptInfo { Name = baseName, Enabled = true });

            return txtPath;
        }

        public void EditScript(GameInfo game)
        {
            if (!HasScript(game))
                return;

            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return;

            // Choose which .txt to edit when multiple exist
            var txtFiles = Directory.GetFiles(inputFolder, "*.txt");
            string? target = null;
            if (txtFiles.Length == 0)
            {
                return;
            }
            else if (txtFiles.Length == 1)
            {
                target = txtFiles[0];
            }
            else
            {
                var dlg = new Microsoft.Win32.OpenFileDialog
                {
                    Title = "Select script to edit",
                    Filter = "Text Scripts (*.txt)|*.txt",
                    InitialDirectory = inputFolder
                };
                if (dlg.ShowDialog() == true) target = dlg.FileName;
            }

            if (!string.IsNullOrEmpty(target) && File.Exists(target))
            {
                Process.Start(new ProcessStartInfo(target) { UseShellExecute = true });
            }
        }

        public void DeleteScript(GameInfo game)
        {
            if (!HasScript(game))
                return;

            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return;

            // If multiple, let user choose which to delete
            var txtFiles = Directory.GetFiles(inputFolder, "*.txt");
            if (txtFiles.Length == 0) return;
            string? targetTxt = null;
            if (txtFiles.Length == 1)
                targetTxt = txtFiles[0];
            else
            {
                var dlg = new Microsoft.Win32.OpenFileDialog
                {
                    Title = "Select script to delete",
                    Filter = "Text Scripts (*.txt)|*.txt",
                    InitialDirectory = inputFolder
                };
                if (dlg.ShowDialog() == true) targetTxt = dlg.FileName;
            }
            if (string.IsNullOrEmpty(targetTxt)) return;
            var baseName = Path.GetFileNameWithoutExtension(targetTxt);
            var ahkPath = Path.Combine(inputFolder, baseName + ".ahk");
            if (File.Exists(targetTxt)) File.Delete(targetTxt);
            if (File.Exists(ahkPath)) File.Delete(ahkPath);

            // remove from manifest
            UpdateManifestScripts(game, man =>
            {
                if (man.InputScripts == null) return;
                man.InputScripts.RemoveAll(s => string.Equals(s.Name, baseName, StringComparison.OrdinalIgnoreCase));
            });

            // Update game info
            game.HasAutoHotKeyScript = false;
        }

        public void LaunchScript(GameInfo game)
        {
            if (!HasScript(game) || !File.Exists(_autoHotKeyExecutable))
                return;

            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return;

            // Load enabled scripts from manifest; if none specified, launch all
            var enabledSet = GetEnabledScripts(game);

            // For each .txt script, mirror to .ahk and launch if enabled
            var txtFiles = Directory.GetFiles(inputFolder, "*.txt");
            foreach (var txt in txtFiles)
            {
                var baseName = Path.GetFileNameWithoutExtension(txt);
                var ahk = Path.Combine(inputFolder, baseName + ".ahk");
                if (enabledSet != null && !enabledSet.Contains(baseName, StringComparer.OrdinalIgnoreCase))
                    continue;
                try
                {
                    var content = File.ReadAllText(txt);
                    File.WriteAllText(ahk, content);
                    Process.Start(new ProcessStartInfo(_autoHotKeyExecutable, $"\"{ahk}\"") { UseShellExecute = true });
                }
                catch
                {
                    // ignore failing scripts to avoid breaking game launch
                }
            }
        }

        public bool HasScript(GameInfo game)
        {
            if (!game.HasAutoHotKeyScript)
                return false;

            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return false;
            return Directory.Exists(inputFolder) &&
                   (Directory.GetFiles(inputFolder, "*.txt").Length > 0 || Directory.GetFiles(inputFolder, "*.ahk").Length > 0);
        }

        /// <summary>
        /// Gets the .txt script path for a game (for editing)
        /// </summary>
        /// <param name="game">The game to get the script path for</param>
        /// <returns>Path to the .txt script file, or null if the game's main folder cannot be determined</returns>
        private string? GetInputFolder(GameInfo game)
        {
            var root = !string.IsNullOrEmpty(game.GameRootPath)
                ? game.GameRootPath
                : FindGameMainFolder(game.FileSystemPath, game.Name);
            if (string.IsNullOrEmpty(root)) return null;
            return Path.Combine(root, "input");
        }

        /// <summary>
        /// Gets the .ahk script path for a game (for execution)
        /// </summary>
        /// <param name="game">The game to get the script path for</param>
        /// <returns>Path to the .ahk script file, or null if the game's main folder cannot be determined</returns>
        public string? GetAhkScriptPath(GameInfo game)
        {
            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return null;
            var ahkFiles = Directory.GetFiles(inputFolder, "*.ahk");
            return ahkFiles.FirstOrDefault();
        }

        /// <summary>
        /// Finds the game's main folder by climbing up the directory tree until we find a folder with the same name as the game
        /// </summary>
        /// <param name="executablePath">Path to the game's executable</param>
        /// <param name="gameName">Name of the game</param>
        /// <returns>Path to the game's main folder, or null if not found</returns>
        private string? FindGameMainFolder(string executablePath, string gameName)
        {
            var currentDir = Path.GetDirectoryName(executablePath);
            if (string.IsNullOrEmpty(currentDir))
                return null;

            // Climb up the directory tree
            while (currentDir != null)
            {
                var folderName = Path.GetFileName(currentDir);
                
                // Check if this folder name matches the game name (case-insensitive)
                if (string.Equals(folderName, gameName, StringComparison.OrdinalIgnoreCase))
                {
                    return currentDir;
                }

                // Move up one level
                var parentDir = Path.GetDirectoryName(currentDir);
                if (parentDir == currentDir) // Reached root
                    break;
                    
                currentDir = parentDir;
            }

            return null;
        }

        private static string SanitizeFileName(string name)
        {
            foreach (var c in Path.GetInvalidFileNameChars())
            {
                name = name.Replace(c, '_');
            }
            return name.Trim();
        }

        // manifest helpers
        private void UpdateManifestScripts(GameInfo game, Action<GameManifest> update)
        {
            if (string.IsNullOrEmpty(game.GameRootPath)) return;
            var manifestPath = Path.Combine(game.GameRootPath, ".moodex_game");
            GameManifest man;
            if (File.Exists(manifestPath))
            {
                var json = File.ReadAllText(manifestPath);
                man = JsonSerializer.Deserialize<GameManifest>(json) ?? new GameManifest();
            }
            else
            {
                man = new GameManifest { Name = game.Name, Guid = game.GameGuid ?? Guid.NewGuid().ToString(), ConsoleId = game.ConsoleId };
            }
            update(man);
            File.WriteAllText(manifestPath, JsonSerializer.Serialize(man, new JsonSerializerOptions { WriteIndented = true }));
        }

        private HashSet<string>? GetEnabledScripts(GameInfo game)
        {
            if (string.IsNullOrEmpty(game.GameRootPath)) return null;
            var manifestPath = Path.Combine(game.GameRootPath, ".moodex_game");
            if (!File.Exists(manifestPath)) return null;
            try
            {
                var json = File.ReadAllText(manifestPath);
                var man = JsonSerializer.Deserialize<GameManifest>(json);
                var enabled = man?.InputScripts?.Where(s => s.Enabled).Select(s => s.Name).ToList();
                return enabled != null ? new HashSet<string>(enabled, StringComparer.OrdinalIgnoreCase) : null;
            }
            catch { return null; }
        }

        public void EditScript(GameInfo game, string scriptName)
        {
            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return;
            var txt = Path.Combine(inputFolder, scriptName + ".txt");
            if (File.Exists(txt)) Process.Start(new ProcessStartInfo(txt) { UseShellExecute = true });
        }

        public void DeleteScript(GameInfo game, string scriptName)
        {
            var inputFolder = GetInputFolder(game);
            if (inputFolder == null) return;
            var txt = Path.Combine(inputFolder, scriptName + ".txt");
            var ahk = Path.Combine(inputFolder, scriptName + ".ahk");
            if (File.Exists(txt)) File.Delete(txt);
            if (File.Exists(ahk)) File.Delete(ahk);
            UpdateManifestScripts(game, man =>
            {
                man.InputScripts?.RemoveAll(s => string.Equals(s.Name, scriptName, StringComparison.OrdinalIgnoreCase));
            });
        }

        public void SetScriptEnabled(GameInfo game, string scriptName, bool enabled)
        {
            UpdateManifestScripts(game, man =>
            {
                man.InputScripts ??= new List<InputScriptEntry>();
                var s = man.InputScripts.FirstOrDefault(x => x.Name.Equals(scriptName, StringComparison.OrdinalIgnoreCase));
                if (s == null)
                {
                    man.InputScripts.Add(new InputScriptEntry { Name = scriptName, Enabled = enabled });
                }
                else
                {
                    s.Enabled = enabled;
                }
            });
        }
    }
}

